services:
  - type: web
    name: youtube-flask-proxy
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: YOUTUBE_API_KEY
        sync: false
